export const mainConfig = {
    "burkinafaso": {
        "Name": "Burkina Faso",
        "Adm1": "Region",
        "Adm2": "Province",
        "Center": [12.7, -1.8],
        "Zoom": [6],
        "indicators": {
            "indicatorb": {
                "Indicator": "Indicator B",
                "Theme": "C",
                "Remark": "",
                "Min": "",
                "Max": "",
                "Delta": "",
                "CHMin": "",
                "CHMax": "",
                "R1": "",
                "R2": "",
                "Y1": "",
                "Y2": "",
                "Resolution": "",
            },
            "indicatorf": {
                "Indicator": "Indicator F",
                "Theme": "B",
                "Remark": "",
                "Min": "",
                "Max": "",
                "Delta": "",
                "CHMin": "",
                "CHMax": "",
                "R1": "",
                "R2": "",
                "Y1": "",
                "Y2": "",
                "Resolution": "",
            },
            "indicatora": {
                "Indicator": "Indicator A",
                "Theme": "A",
                "Remark": "",
                "Min": "",
                "Max": "",
                "Delta": "",
                "CHMin": "",
                "CHMax": "",
                "R1": "",
                "R2": "",
                "Y1": "",
                "Y2": "",
                "Resolution": "",
            },
        }
    },
    "india": {
        "Name": "India",
        "Adm1": "State",
        "Adm2": "District",
        "Center": [22.9, 79.6],
        "Zoom": [4],
        "indicators": {
            "indicatori": {
                "Indicator": "Indicator I",
                "Theme": "A",
                "Remark": "",
                "Min": "",
                "Max": "",
                "Delta": "",
                "CHMin": "",
                "CHMax": "",
                "R1": "",
                "R2": "",
                "Y1": "",
                "Y2": "",
                "Resolution": "",
            },
            "indicatorn": {
                "Indicator": "Indicator N",
                "Theme": "B",
                "Remark": "",
                "Min": "",
                "Max": "",
                "Delta": "",
                "CHMin": "",
                "CHMax": "",
                "R1": "",
                "R2": "",
                "Y1": "",
                "Y2": "",
                "Resolution": "",
            },
            "indicatord": {
                "Indicator": "Indicator D",
                "Theme": "B",
                "Remark": "",
                "Min": "",
                "Max": "",
                "Delta": "",
                "CHMin": "",
                "CHMax": "",
                "R1": "",
                "R2": "",
                "Y1": "",
                "Y2": "",
                "Resolution": "",
            },
        }
    },
    "kenya": {
        "Name": "Kenya",
        "Adm1": "County",
        "Adm2": "Sub-county",
        "Center": [0.6, 37.8],
        "Zoom": [6],
        "indicators": {
            "indicatork": {
                "Indicator": "Indicator K",
                "Theme": "B",
                "Remark": "",
                "Min": "",
                "Max": "",
                "Delta": "",
                "CHMin": "",
                "CHMax": "",
                "R1": "",
                "R2": "",
                "Y1": "",
                "Y2": "",
                "Resolution": "",
            },
            "indicatore": {
                "Indicator": "Indicator E",
                "Theme": "A",
                "Remark": "",
                "Min": "",
                "Max": "",
                "Delta": "",
                "CHMin": "",
                "CHMax": "",
                "R1": "",
                "R2": "",
                "Y1": "",
                "Y2": "",
                "Resolution": "",
            },
            "indicatorn": {
                "Indicator": "Indicator N",
                "Theme": "A",
                "Remark": "",
                "Min": "",
                "Max": "",
                "Delta": "",
                "CHMin": "",
                "CHMax": "",
                "R1": "",
                "R2": "",
                "Y1": "",
                "Y2": "",
                "Resolution": "",
            },
        }
    },
    "nigeria": {
        "Name": "Nigeria",
        "Adm1": "State",
        "Adm2": "Local Government Area",
        "Center": [9.5, 8.0],
        "Zoom": [6],
        "indicators": {
            "indicatorn": {
                "Indicator": "Indicator N",
                "Theme": "B",
                "Remark": "",
                "Min": "",
                "Max": "",
                "Delta": "",
                "CHMin": "",
                "CHMax": "",
                "R1": "",
                "R2": "",
                "Y1": "",
                "Y2": "",
                "Resolution": "",
            },
            "indicatorg": {
                "Indicator": "Indicator G",
                "Theme": "A",
                "Remark": "",
                "Min": "",
                "Max": "",
                "Delta": "",
                "CHMin": "",
                "CHMax": "",
                "R1": "",
                "R2": "",
                "Y1": "",
                "Y2": "",
                "Resolution": "",
            },
            "indicatora": {
                "Indicator": "Indicator A",
                "Theme": "A",
                "Remark": "",
                "Min": "",
                "Max": "",
                "Delta": "",
                "CHMin": "",
                "CHMax": "",
                "R1": "",
                "R2": "",
                "Y1": "",
                "Y2": "",
                "Resolution": "",
            },
        }
    }
}

export const indicatorDef = {
    "indicatora": {
        "Indicator": "Indicator A",
        "Theme": "A",
        "Definition": "",
        "Unit": "",
        "Denominator": "",
        "Proportional": "",
    },
    "indicatorb": {
        "Indicator": "Indicator B",
        "Theme": "B",
        "Definition": "",
        "Unit": "",
        "Denominator": "",
        "Proportional": "",
    },
    "indicatord": {
        "Indicator": "Indicator D",
        "Theme": "S",
        "Definition": "",
        "Unit": "",
        "Denominator": "",
        "Proportional": "",
    },
    "indicatore": {
        "Indicator": "Indicator E",
        "Theme": "S",
        "Definition": "",
        "Unit": "",
        "Denominator": "",
        "Proportional": "",
    },
    "indicatorf": {
        "Indicator": "Indicator F",
        "Theme": "S",
        "Definition": "",
        "Unit": "",
        "Denominator": "",
        "Proportional": "",
    },
    "indicatorg": {
        "Indicator": "Indicator G",
        "Theme": "B",
        "Definition": "",
        "Unit": "",
        "Denominator": "",
        "Proportional": "",
    },
    "indicatori": {
        "Indicator": "Indicator I",
        "Theme": "S",
        "Definition": "",
        "Unit": "",
        "Denominator": "",
        "Proportional": "",
    },
    "indicatork": {
        "Indicator": "Indicator K",
        "Theme": "A",
        "Definition": "",
        "Unit": "",
        "Denominator": "",
        "Proportional": "",
    },
    "indicatorn": {
        "Indicator": "Indicator N",
        "Theme": "B",
        "Definition": "",
        "Unit": "",
        "Denominator": "",
        "Proportional": "",
    },
}